/**
 * This class is generated by jOOQ
 */
package com.example.employee.db.jooq.domain;


import com.example.employee.db.jooq.domain.tables.Employee;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in enterprise
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>enterprise.employee</code>.
     */
    public static final Employee EMPLOYEE = com.example.employee.db.jooq.domain.tables.Employee.EMPLOYEE;
}
